KML+KMZ and Gradle Tests
dataiku/dss-plugin-kml-format pull request #1
Opened 2020-09-14 09:58 UTC by tdesfont

Started from the existing KML plugin, working on adding read of KMZ files and added tests using Gradle.

2020-10-15 08:52 UTC, tdesfont commented
**NB**: Still have to create a test project, check documentation and code

2020-10-16 16:02 UTC, tdesfont commented
**Status on that PR:** The unit tests on the KMZ are failing, I don't know exactly why since the extracted content looks ok. I have put the KML and KMZ in the same file so that the KML format in DSS can handle both formats now. Thanks JF for the guava fix and the help with gradle. I will update you as soon as the PR can be reviewed.

2020-10-19 10:19 UTC, tdesfont commented
I set up a test project on dku17: http://dku17.dataiku.com:30800/projects/PLUGINTESTKMLKMZ/flow/

2020-10-21 08:57 UTC, jfyuen requested changes
If moving to gradle, you can also remove the `build.xml` for Ant.

Only looked at the gradle build, not the implementation. 
You may also want to replace all those `System.out.Println()` by a logger.

2020-10-21 08:57 UTC, jfyuen commented on build.gradle
> +            srcDirs = ['java-formats/kml-format_kml/src']
We already talked about it, it seems weird to me that the src files are in `java-formats/kml-format_kml/src` and tests files in `tests/java/unit`.
Have a look [here](https://docs.gradle.org/current/userguide/organizing_gradle_projects.html) at how gradle expects directories

2020-10-21 08:57 UTC, jfyuen commented on build.gradle
> +	id 'java'
May want to use the [java-library](https://docs.gradle.org/current/userguide/java_library_plugin.html) plugin instead

2020-10-21 08:57 UTC, jfyuen commented on build.gradle
> +    into 'java-lib'
Also extends the `clean` task to delete that directory:
```
clean.doLast {
    delete 'java-lib'
    delete 'lib'
}
```

2020-10-21 09:02 UTC, tdesfont commented
Hey @jfyuen @MayeulRousselet you can start the review, I am making sure that test flows are available today, do not hesitate to ping me

2020-10-21 09:03 UTC, tdesfont commented
@jfyuen I just saw your comments above, thanks !

2020-10-26 19:13 UTC, MayeulRousselet requested changes

2020-10-26 19:13 UTC, MayeulRousselet commented on README.md
> +- Expose a KML Parser
And KMZ?

2020-10-26 19:13 UTC, MayeulRousselet commented on README.md
> +To build and test the plugin using Gradle, do:
```suggestion
To test the plugin using Gradle, do:
./gradlew test
```

2020-10-26 19:13 UTC, MayeulRousselet commented on README.md
> +## Testing the plugin
The paragraph is not very clear, the title is "Testing the plugin" whereas what you describe is the build & release process. Make a "build the plugin" paragraph, and after a "Run the unit tests" paragraph.

2020-10-26 19:13 UTC, MayeulRousselet commented on README.md
> +Once done, a zip of the plugin is created in the dist folder. This archive will be the one used by DSS.
```suggestion
Once done, a zip of the plugin is created in the dist folder. This archive will be the one used by DSS to install the plugin.
```

2020-10-26 19:13 UTC, MayeulRousselet commented on build.gradle
> +            srcDirs = ['java-formats/kml-format_kml/src']
Sorry to disturb maven purists (I am one of them), but that's how things works with Java components in plugins.

2020-10-26 19:13 UTC, MayeulRousselet commented on java-formats/kml-format_kml/src/com/dataiku/dss/formats/kml/KMLFormat.java
> +    // private static Logger logger = Logger.getLogger("dku");
remove comment

2020-10-26 19:13 UTC, MayeulRousselet commented on java-formats/kml-format_kml/src/com/dataiku/dss/formats/kml/KMLFormat.java
> +    protected static DKULogger logger = DKULogger.getLogger("dku");
Change the visibility from protected to private.

2020-10-26 19:13 UTC, MayeulRousselet commented on java-formats/kml-format_kml/src/com/dataiku/dss/utils/KMLParser.java
> +    public static Logger logger = Logger.getLogger("dku");
Change the visibility from public to private and put the declaration at the end of the class.

2020-10-26 19:13 UTC, MayeulRousselet commented on java-formats/kml-format_kml/src/com/dataiku/dss/utils/KMLParser.java
> +        logger.info("Children of" + parent);
remove the logging

2020-10-26 19:13 UTC, MayeulRousselet commented on java-formats/kml-format_kml/src/com/dataiku/dss/utils/KMLParser.java
> +    public String getTextContent(Node e){return e.getTextContent();}
Remove this method and inline the calls (can be done in IntelliJ by selecting the method, right click "Refactor" > inline method)

2020-10-26 19:13 UTC, MayeulRousselet commented on java-formats/kml-format_kml/src/com/dataiku/dss/utils/KMLParser.java
> +            if (txt != null) r.put(cf.column(columnName), txt);
```suggestion
            if (txt != null) {
                 r.put(cf.column(columnName), txt);
            }
```

2020-10-26 19:13 UTC, MayeulRousselet commented on java-formats/kml-format_kml/src/com/dataiku/dss/utils/KMLParser.java
> +        //assert(node.getLocalName().equals("Placemark"));
remove comment

2020-10-26 19:13 UTC, MayeulRousselet commented on java-formats/kml-format_kml/src/com/dataiku/dss/utils/KMLParser.java
> +    private void parsePlacemark(Node node, ProcessorOutput out, ColumnFactory cf, RowFactory rf) throws Exception {
The formatting of this method is ugly (it is a remain of the old plugin), remove the blank spaces.

2020-10-26 19:13 UTC, MayeulRousselet commented on java-formats/kml-format_kml/src/com/dataiku/dss/utils/KMLParser.java
> +        cf.column("geom");
Redondant, cf.column("geom") will be called in the block below. To remove

2020-10-26 19:13 UTC, MayeulRousselet commented on java-formats/kml-format_kml/src/com/dataiku/dss/utils/KMLParser.java
> +        cf.column("id");
Redondant, cf.column("id") will be called in putAttrValueIfExists. To remove

2020-10-26 19:13 UTC, MayeulRousselet commented on java-formats/kml-format_kml/src/com/dataiku/dss/utils/KMLParser.java
> +                String coordsTxt = getTextContent(coordsElt);
As getFirstNodeByTagName can return a null value, test if coordsElt != null

2020-10-26 19:13 UTC, MayeulRousselet commented on java-formats/kml-format_kml/src/com/dataiku/dss/utils/KMLParser.java
> +        {
Anonymous blocks in Java are to be avoided.
For a better readability, create a private method "extractAndSetPoint"

2020-10-26 19:13 UTC, MayeulRousselet commented on java-formats/kml-format_kml/src/com/dataiku/dss/utils/KMLParser.java
> +                Coords coords = new Coords(Double.parseDouble(chunks[1]), Double.parseDouble(chunks[0]));
Same here, 
```suggestion
                if(chunks != null && chunks.size() >=2) {
                      Coords coords = new Coords(Double.parseDouble(chunks[1]), Double.parseDouble(chunks[0]));
                      r.put(cf.column("geom"), coords.toWKT());
                 }
```

2020-10-26 19:13 UTC, MayeulRousselet commented on java-formats/kml-format_kml/src/com/dataiku/dss/utils/KMLParser.java
> +        {
Extract this block into a extractAndSetLine

2020-10-26 19:13 UTC, MayeulRousselet commented on java-formats/kml-format_kml/src/com/dataiku/dss/utils/KMLParser.java
> +                String coordsTxt = getTextContent(coordsElt);
Same, test for if coordsElt is not null

2020-10-26 19:13 UTC, MayeulRousselet commented on java-formats/kml-format_kml/src/com/dataiku/dss/utils/KMLParser.java
> +                String[] points = StringUtils.splitByWholeSeparator(coordsTxt,  " ");
Same, test if points is not null

2020-10-26 19:13 UTC, MayeulRousselet commented on java-formats/kml-format_kml/src/com/dataiku/dss/utils/KMLParser.java
> +                    if (StringUtils.isBlank(point)) continue;
```suggestion
                    if (StringUtils.isBlank(point)){
                        continue;
                   }
```

2020-10-26 19:13 UTC, MayeulRousselet commented on java-formats/kml-format_kml/src/com/dataiku/dss/utils/KMLParser.java
> +                    pointsStr.add(chunks[1] + " " + chunks[0]);
```suggestion
if(chunks != null && chunks.size() >=2) {
                    pointsStr.add(chunks[1] + " " + chunks[0]);
               }
```

2020-10-26 19:13 UTC, MayeulRousselet commented on java-formats/kml-format_kml/src/com/dataiku/dss/utils/KMLParser.java
> +                r.put(cf.column("geom"), "LINESTRING(" + StringUtils.join(pointsStr, ",") + ")");
Here, test that pointsStr has more than 2 elements. As my grandpa said, "Can't create a line out of one point man!"

2020-10-26 19:13 UTC, MayeulRousselet commented on java-formats/kml-format_kml/src/com/dataiku/dss/utils/KMLParser.java
> +            Element extendedDataElt = getFirstNodeByTagName(e, "ExtendedData");
Saaaame, create a method call extractAndSetExtendedData

2020-10-26 19:13 UTC, MayeulRousselet commented on java-formats/kml-format_kml/src/com/dataiku/dss/utils/KMLParser.java
> +                NodeList nl = extendedDataElt.getElementsByTagName("Data");
Test for nullability of nl

2020-10-26 19:13 UTC, MayeulRousselet commented on tests/java/unit/com/dataiku/dss/formats/kml/KMLFormatTest.java
> +    private ColumnFactory colFactory = new StreamColumnFactory();
As ColumnFactory and RowFactory maintains an internal state (the columns created and the rows), best is to init both member in setupDSS(), as we do for kmlFormatInput

2020-10-26 19:13 UTC, MayeulRousselet commented on tests/java/unit/com/dataiku/dss/formats/kml/KMLFormatTest.java
> +    public void testReadFile() throws IOException {
This test has no assert. Either add one or remove the test

2020-10-27 13:30 UTC, MayeulRousselet requested changes

2020-10-27 13:30 UTC, MayeulRousselet commented on README.md
> +## Building the plugin
Build the plugin

2020-10-27 13:30 UTC, MayeulRousselet commented on README.md
> +## Testing the plugin
Test the plugin

2020-10-27 13:30 UTC, MayeulRousselet commented on README.md
> +- Expose a KML/KMZ parser
Could be more precise: What the plugin does?

2020-10-27 13:30 UTC, MayeulRousselet commented on java-formats/kml-format_kml/src/com/dataiku/dss/utils/KMLParser.java
> +        for (int i=0; i < parent.getChildNodes().getLength(); i++){
Remove this logging too

2020-10-27 13:30 UTC, MayeulRousselet commented on java-formats/kml-format_kml/src/com/dataiku/dss/utils/KMLParser.java
> +                for (String point : points) {
test for points nullability

2020-10-27 13:30 UTC, MayeulRousselet commented on java-formats/kml-format_kml/src/com/dataiku/dss/utils/KMLParser.java
> +                String[] chunks = coordsTxt.split(",");
Check if coordsTxt is not null

2020-10-27 13:30 UTC, MayeulRousselet commented on java-formats/kml-format_kml/src/com/dataiku/dss/utils/KMLParser.java
> +                String[] points = StringUtils.splitByWholeSeparator(coordsTxt,  " ");
Check if coordsTxt is not null

2020-10-27 13:30 UTC, MayeulRousselet commented on java-formats/kml-format_kml/src/com/dataiku/dss/utils/KMLParser.java
> +        Element e = (Element)node;
Test if node can be casted to Element
```suggestion
        if( node instanceof Element) {
              Element e = (Element)node;
              ...
       }
```

2020-10-27 13:30 UTC, MayeulRousselet commented on java-formats/kml-format_kml/src/com/dataiku/dss/utils/KMLParser.java
> +                    Element dataElt = (Element)nl.item(i);
Idem, test if nb.item(i) can be casted to Element

2020-10-27 13:30 UTC, MayeulRousselet commented on java-formats/kml-format_kml/src/com/dataiku/dss/utils/KMLParser.java
> +                Element childElt = (Element)childNode;
Idem, test if childNode can be casted to Element

2020-10-27 16:21 UTC, MayeulRousselet approved these changes

2020-10-27 16:24 UTC, MayeulRousselet requested changes
Faut updater le numero de version dans le MAkefile et le plugin.json

2020-10-28 15:58 UTC, merged